services:
  db:
    container_name: backend
    image: postgres:latest
    env_file:
      - ../.env
  #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    env_file:
      - ../.env
    ports:
      - "5050:80"
    restart: always